# -*- coding: utf-8 -*-
"""FullExpressionParsing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLIr3TAbXqHdQurDh4XU9ebyFQHUvP_4
"""

from singleexpressionconversion import numpyString
import sys
import re

def numpyStringFullFile():
  s = sys.argv[1]
  input = open(s,'r').read().strip().replace('\n','')

  sumorder = []
  sumorder = [item for item in input if item == '+' or item == '-' ]

  input = re.split('[-+]', input)
  input = [x for x in input if x != '']

  if len(sumorder) + 1 == len(input):
        sumorder = ['+'] + sumorder
  elif len(sumorder) != len(input):
        print("There seems to be some discrepancy vis-a-vis your addition and/or subtraction symbols.")

  retval = ''
  
  for i in range(0,len(input)):
      c = sumorder[i]
      if c == '-':
          summand = """(-1)*(""" + numpyString(input[i]) + """)"""
      else :
          summand = numpyString(input[i])
      
      retval = retval + summand + """ + """
  if retval[-2] == '+':
    retval = retval[:-3]
  return retval


s = str(sys.argv[1])
s = s[:-4]
#print(s)
f = "GeneratedCodefor{}.py".format(s)
file = open(f,"w") 
 
file.write("import numpy as np") 
file.write('\n') 
file.write(numpyStringFullFile()) 

file.close()
